language: objective-c
osx_image: xcode7.3
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - PROJECT=SwiftLinkPreview.xcodeproj
script:
  - xcodebuild -project SwiftLinkPreview.xcodeproj -scheme SwiftLinkPreview         -destination "OS=9.3,name=iPhone 6S"            -sdk "iphonesimulator9.3"   RUN_TESTS="YES" BUILD_EXAMPLE="NO" POD_LINT="NO" -configuration Debug ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test | xcpretty -c;
  - xcodebuild -project SwiftLinkPreview.xcodeproj -scheme SwiftLinkPreviewWatchOS  -destination "OS=2.2,name=Apple Watch - 42mm"   -sdk "watchsimulator2.2"    RUN_TESTS="NO"  BUILD_EXAMPLE="NO" POD_LINT="NO" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty -c;
  - xcodebuild -project SwiftLinkPreview.xcodeproj -scheme SwiftLinkPreviewTvOS     -destination "OS=9.2,name=Apple TV 1080p"         -sdk "appletvsimulator9.2"  RUN_TESTS="YES" BUILD_EXAMPLE="NO" POD_LINT="NO" -configuration Debug ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test | xcpretty -c;
  - xcodebuild -project SwiftLinkPreview.xcodeproj -scheme SwiftLinkPreviewMacOS    -destination "arch=x86_64"                      -sdk "macosx10.11"          RUN_TESTS="YES" BUILD_EXAMPLE="NO" POD_LINT="NO" -configuration Debug ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test | xcpretty -c;
